### ISSUE TITLE
Is it possible to filter trees, houses and store them in separate files individually for LAS files?

### ISSUE THREAD

**Issue by niranjanreddy891** [davidcaron/pclpy#25]
@davidcaron, can you please help me with this

**Comment by davidcaron** [comment]
Definitely possible, but not straight forward. It depends on a lot of factors, and requires a lot of thinking and experimenting. I'm sorry if I'm being too bread in my answer, but you'll have to try to do some research on your own, as I don't have time you help you on this... It's a deep subject and you'll find a lot of articles online.
