### ISSUE TITLE
pip install pclpy in windows fails

### ISSUE THREAD

**Issue by barlaensdoonn** [davidcaron/pclpy#37]
Windows 10
Python 3.6.4
Git Bash 
(although it didn't work from command prompt either)

pip install pclpy fails with:
```
$ pip install pclpy
Collecting pclpy
  Could not find a version that satisfies the requirement pclpy (from versions: )
No matching distribution found for pclpy
```

**Comment by barlaensdoonn** [comment]
weird it just worked from powershell

**Comment by barlaensdoonn** [comment]
i guess I'll close this one but if i've ever had more of a case of the baffles i don't know when

**Comment by davidcaron** [comment]
Very weird... 'python --version' in cmd.exe gives 3.6.4?

**Comment by barlaensdoonn** [comment]
![Capture](https://user-images.githubusercontent.com/5253980/54729664-09738080-4b42-11e9-9590-390e16bddcc3.PNG)
