### ISSUE TITLE
pip install requuirements error (Windows)

### ISSUE THREAD

**Issue by Bastiiiiii** [davidcaron/pclpy#40]
Hello,

I am quite new to python and I want to install the Point Cloud Library package.
I use PyCharm, Python 3.7.3 and Windows 10, I tried to install the package through the Terminal in PyCharm and 'pip install pclpy'.

This ist the respond:

Collecting pclpy
  ERROR: Could not find a version that satisfies the requirement pclpy (from versions: none)
ERROR: No matching distribution found for pclpy

Can you help me out?

Thank you!

**Comment by davidcaron** [comment]
It's only available for python 3.6 on pypi. Thank you for trying it out.
