### ISSUE TITLE
Anaconda channel does not contain pclpy

### ISSUE THREAD

**Issue by maxpfingsthorn** [davidcaron/pclpy#60]
I was very happy to see your recent commit that pclpy will be available through conda on Windows and Linux! Great timing for the new semester. I am looking forward to sharing your api for PCL with my students.

At the moment, pclpy does not seem to be in your channel yet:
https://conda.anaconda.org/davidcaron/linux-64
https://conda.anaconda.org/davidcaron/win-64

The only package there is osmctools.

Can you say when the package will be available?

**Comment by davidcaron** [comment]
Hi, I just released version 0.12.0 on the channels you listed. I still had some small build issues that I finally got some time to fix. I still have a small problem with python 3.8 on windows, but 3.6 and 3.7 work and 3.6 to 3.8 are supported on linux.

I'm closing this issue, just reopen it or open another one if you encounter problems with the release.
