### ISSUE TITLE
Convert pclpy.pcl.PointCloud.PointXYZ object into numpy array?

### ISSUE THREAD

**Issue by ibrahimLearning** [davidcaron/pclpy#61]
How can I convert pclpy.pcl.PointCloud.PointXYZ object into numpy array?

I read las file 
point3d = pclpy.io.las.read(pcdF, "PointXYZ")
How can I convert point3d into numpy array.

**Comment by rbrigden** [comment]
From the readme

> You can get a numpy view of point cloud data using python properties (e.g. `cloud.x` or `cloud.xyz`)

**Comment by szx0112** [comment]
Hi @rbrigden, how could we construct a point cloud object using numpy array. I am also confuse how to compute/extract normals. Any comment is appreciated.
