### ISSUE TITLE
ImportError: libflann.so.1.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MengHao666** [davidcaron/pclpy#62]
I try to install it in ubuntu16.04, python3.6 now using "conda install -c conda-forge -c davidcaron pclpy"
  and now i got erros  like the following:
    "Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 23:51:54) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pclpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haomeng/anaconda3/envs/py36/lib/python3.6/site-packages/pclpy/__init__.py", line 3, in <module>
    import pclpy.pcl as pcl
ImportError: libflann.so.1.9: cannot open shared object file: No such file or directory
>>> 
"

How can i solve such problem? Should i build it from source？
Ｏr it cannot support ubuntu now?

**Comment by MengHao666** [comment]
Ｄoes anyone else meet same problem?

**Comment by wisper181** [comment]
hello,I get the same problem.Have U solved the BUG?
Any suggestion may be helpful
Thanks in advance

**Comment by MengHao666** [comment]
I am sorry that I fogot it. ---- Replied Message ***@***.***>Date04/27/2021 16:09 ***@***.***> CcHao ***@***.******@***.***>SubjectRe: [davidcaron/pclpy] ImportError: libflann.so.1.9: cannot open shared object file: No such file or directory (#62)
hello,I get the same problem.Have U solved the BUG?
Any suggestion may be helpful
Thanks in advance

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/davidcaron/pclpy/issues/62#issuecomment-827408583",
"url": "https://github.com/davidcaron/pclpy/issues/62#issuecomment-827408583",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
